version: '3'
services:
  django:
    build: 
      context: url_shortner
      dockerfile: Dockerfile
    image: 'backend:latest'
    container_name: 'django_url_shortener'
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_HOST=postgresqldb
      - MODE=Development-docker
    ports:
      - 8000:8000
    volumes:
      - ./url_shortner:/app
    depends_on:
      - postgresqldb
    networks:
      - app-network
    command:
      - /bin/sh
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
  postgresqldb:
    image: 'bitnami/postgresql:latest'
    container_name: url_shortner-postgresqldb
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRESQL_USERNAME=$DB_USER
      - POSTGRESQL_PASSWORD=$DB_PASSWORD
      - POSTGRESQL_DATABASE=$DB_NAME
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - dbdata:/bitnami/postgresql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: